name: Python package

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - "*"

jobs:

  pyenv-build:
    name: pyenv ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["macos-latest"]
        python-version: ["3.7.5"]
        
    steps:
      - uses: actions/checkout@v2   
      - uses: "gabrielfalcao/pyenv-action@v6" 
        with:
          default: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install spatialindex
          python3 -m pip install --upgrade pip
          pyenv local ${{ matrix.python-version }} && python3 -mvenv .venv${{ matrix.python-version }}
      - name: Install pvtrace
        shell: bash -l {0}
        run: |
          pip3 install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip3 install pytest
          pytest tests
          
  conda-build:
    name: Conda ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.1.2
        with:
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge Rtree
          python -m pip install --upgrade pip
      - name: Install pvtrace
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest tests
